### ISSUE TITLE
error/empty state on discover

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#21]
Probably never going to be the case that "Discover" is blank, but would it be good to have an empty state here, as a failsafe in case articles fail to load or some other error?

<img width="662" alt="image" src="https://user-images.githubusercontent.com/10856173/77515296-7eeced80-6e35-11ea-924f-d5064cba7a6c.png">

**Comment by amorriscode** [comment]
Closing this issue. All pages need empty/error states developed so this will be resolved in the future.
