### ISSUE TITLE
published articles seem to be accompanied by a draft (even after publishing)

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#22]
I had a partial draft save as a draft, and remain there, even after I published the article. This exists simultaneously with the published article:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/10856173/77515550-f3279100-6e35-11ea-81c1-c175fb197bfb.png">

Realized I might've been wrong in the last QA: The blank drafts were not empty drafts that were abandoned. Every new article I publish is bringing with it a blank draft (3 for 3 in this example):

<img width="804" alt="image" src="https://user-images.githubusercontent.com/10856173/77515637-18b49a80-6e36-11ea-9cee-c584ab4d2bd2.png">

**Comment by amorriscode** [comment]
Closing; cannot reproduce.
