### ISSUE TITLE
logged out states/permissions

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#24]
After logging out, I can still see "delete" and other features that should be exclusive to the other himself.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/10856173/77516263-50701200-6e37-11ea-92e6-c8a30dfad6cf.png">

Can also see Edit/Delete on another writer's profile:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/10856173/77516340-739ac180-6e37-11ea-9646-f42d5fc22423.png">

Additional: The first time I clicked on an author's page it showed me a logged out state, even though I was still logged in. I could not replicate this.

**Comment by amorriscode** [comment]
Most of these are expected as there is currently no logic based on the actions. 👍 

Will fix soon.
