### ISSUE TITLE
word length

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#25]
What do you think of eliminating "written by" and just having author name for simplicity and cleanliness? Gets a little clunky sometimes. 

For time published, even "less than a minute ago" or the word "about" + time, feel verbose or end up with stylistic issues.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/10856173/77516564-e015c080-6e37-11ea-9604-a5a36d754b63.png">

**Comment by amorriscode** [comment]
I suppose we can. I personally like `written by` and then having it hidden for smaller screen sizes.

The time library used adds **less than...** and **about** so not much to be done there. I only add the word **ago**.
