### ISSUE TITLE
default view too large on my resolution

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#26]
default view (command + 0) in my resolution feels too zoomed in:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/10856173/77516737-210dd500-6e38-11ea-8e79-15bd331d4eee.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/10856173/77516758-29661000-6e38-11ea-8776-f5756a55b2f2.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/10856173/77516792-3420a500-6e38-11ea-81a5-e4f3a24b226a.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/10856173/77516817-3be04980-6e38-11ea-81d5-9f063d61673f.png">

______

default view on new discover:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/10856173/77594938-10e80b00-6eb5-11ea-8cc6-2dd5f9e13f96.png">

but looks pretty golden with (COMMAND-)x2

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/10856173/77595000-3aa13200-6eb5-11ea-8f58-e29ca0bb23fa.png">

**Comment by amorriscode** [comment]
Closing due to your 👴 settings on your MacBook.
