### ISSUE TITLE
"save as draft" or "save and publish"

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#32]
Should there be a "Save As Draft" button? If I'm writing a draft and want to move on without being ready to publish, I feel like I would want to manually force a save or at least know for sure when my last auto-save was. This is another spot where I feel a bit lost without navigation.

Discussion brought up the idea of "save and publish" when editing a published article.

**Comment by amorriscode** [comment]
This ticket should be resolved, minus the change in copy. Will confirm.
