### ISSUE TITLE
article got published without body? 

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#35]
I'm not sure how this article got published without a body, didn't realize until after playing around in Discover. 

have not been able to replicate yet. 

<img width="628" alt="image" src="https://user-images.githubusercontent.com/10856173/77582516-c22e7700-6e9c-11ea-840e-9baf388b1614.png">

**Comment by amorriscode** [comment]
I kind of feel like this is resolved but will leave it open until I confirm.

**Comment by amorriscode** [comment]
Closing, can't reproduce. Probably an old bug.
