### ISSUE TITLE
editor should accept line breaks when pasting

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#37]
a) The Editor should accept line breaks when pasting in text. When I tried to paste articles in (which we will be doing in migration), it came in as a wall of text. 

b) Should there be a limit to have many line breaks can be saved like on a reddit post? I could manually put in 20 line breaks and create a huge empty gap in an article.

**Comment by amorriscode** [comment]
Someone could use linebreaks...













for suspense! I don't think we should limit them.
