### ISSUE TITLE
articles page showing error on first load, works on refresh

### ISSUE THREAD

**Issue by codinglegend** [getbard/webapp#40]
first load:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/10856173/77595801-64f3ef00-6eb7-11ea-8bd8-8f6b4a781b78.png">

after refresh:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/10856173/77595813-70471a80-6eb7-11ea-9a7e-bfb0e615de0b.png">

right now happens almost 100% of the time when I go into articles page. one way to recreate it is to go into a specific article, then click into "articles" to see the error.

**Comment by amorriscode** [comment]
I think it has to do with your token being expired.

**Comment by amorriscode** [comment]
Fixed (was missing an index on firestore). 🎉
